name             'sshenv'
maintainer       'Paolo Sechi'
maintainer_email 'sekipaolo@gmail.com'
license          'Apache License, Version 2.0'
description      'Setup ssh environment under linux sistem'
long_description 'Installs/Configures sshenv'
version          '0.1.0'
